# Generated by Django 5.0.6 on 2024-06-27 23:08

import restaurant_search.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("opening_hours", models.TextField(default=None)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=restaurant_search.models.restaurant_image_file_path,
                    ),
                ),
            ],
        ),
    ]
