# Generated by Django 5.0.6 on 2024-06-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="opening_hours",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
