# Generated by Django 5.0.6 on 2024-07-08 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("text", models.TextField(blank=True, max_length=1000, null=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="restaurant",
            name="unique_restaurant",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="images",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="opening_hours",
        ),
        migrations.AddField(
            model_name="image",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurant_search.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="google_url",
            field=models.CharField(
                blank=True, default=None, max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="location",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="photos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurants",
                to="restaurant_search.image",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="total_users_ratings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="website_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="weekdays_opening_hours",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="address",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="unique_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="restaurant_search.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="reviews",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurants",
                to="restaurant_search.review",
            ),
        ),
    ]
