# Generated by Django 5.0.6 on 2024-06-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0002_alter_restaurant_opening_hours"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="restaurant",
            constraint=models.UniqueConstraint(
                fields=("name", "address"), name="unique_restaurant"
            ),
        ),
    ]
