# Generated by Django 5.0.6 on 2024-07-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant_search",
            "0002_review_remove_restaurant_unique_restaurant_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="location",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=10000, max_digits=10000, null=True
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=10000, max_digits=10000, null=True
            ),
        ),
    ]
