# Generated by Django 5.0.6 on 2024-06-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0003_restaurant_unique_restaurant"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="unique_id",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
