# Generated by Django 5.0.6 on 2024-07-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0004_remove_restaurant_weekdays_opening_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="opening_hours_weekdays",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
