# Generated by Django 5.0.6 on 2024-06-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0004_restaurant_unique_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="image",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="outdoor_images",
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="unique_id",
            field=models.CharField(
                default="Sorry, we dont have address in our database.", max_length=255
            ),
        ),
    ]
