# Generated by Django 5.0.6 on 2024-06-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant_search",
            "0005_remove_restaurant_image_restaurant_outdoor_images_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="outdoor_images",
            new_name="images",
        ),
    ]
