# Generated by Django 5.0.6 on 2024-07-08 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0005_restaurant_opening_hours_weekdays"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="restaurant",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="photos",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="reviews",
        ),
        migrations.AddField(
            model_name="image",
            name="restaurants",
            field=models.ManyToManyField(
                blank=True, related_name="photos", to="restaurant_search.restaurant"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="google_url",
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="opening_hours_weekdays",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="unique_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="website_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="author_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="restaurant_search.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
