# Generated by Django 5.0.6 on 2024-07-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0007_remove_image_restaurants_image_restaurants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="restaurants",
            new_name="restaurant",
        ),
    ]
