# Generated by Django 5.0.6 on 2024-07-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0008_rename_restaurants_image_restaurant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="open_now",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
