# Generated by Django 5.0.6 on 2024-07-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0010_image_unique_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="main_photo",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
