# Generated by Django 5.0.6 on 2024-07-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0011_restaurant_main_photo"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "author_name", "text", "rating", "created_at"),
                name="unique_review",
            ),
        ),
    ]
