# Generated by Django 5.0.6 on 2024-07-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0013_remove_review_unique_review_review_unique_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "unique_name"), name="unique_review"
            ),
        ),
    ]
