# Generated by Django 5.0.6 on 2024-07-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0014_review_unique_review"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="unique_review",
        ),
    ]
