# Generated by Django 5.0.6 on 2024-07-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0015_remove_review_unique_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="unique_name",
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
