# Generated by Django 5.0.6 on 2024-07-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0016_alter_review_unique_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
