# Generated by Django 5.0.6 on 2024-07-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favourite",
        ),
    ]
