# Generated by Django 5.0.6 on 2024-07-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0018_image_contrib_url"),
        ("user", "0003_favouriterestaurants"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavouriteRestaurants",
            new_name="Favourite",
        ),
    ]
