# Generated by Django 5.0.6 on 2024-07-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_search", "0018_image_contrib_url"),
        ("user", "0004_rename_favouriterestaurants_favourite"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="favourite",
            constraint=models.UniqueConstraint(
                fields=("user", "restaurant"), name="unique_favourite"
            ),
        ),
    ]
