# Generated by Django 5.0.6 on 2024-07-10 16:39

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_favourite_unique_favourite"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.profile_picture_file_path
            ),
        ),
    ]
