# Generated by Django 5.0.6 on 2024-07-12 14:52

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_remove_user_profile_picture_profilepicture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.models.profile_picture_file_path
            ),
        ),
        migrations.DeleteModel(
            name="ProfilePicture",
        ),
    ]
